"""Vulnerability modules for sslpwn."""
from .beast import BeastAttack
from .lucky13 import Lucky13Attack
from .breach import BreachAttack
from .poodle import PoodleAttack
from .crime import CrimeAttack
from .heartbleed import HeartbleedAttack
from .ticketbleed import TicketbleedAttack
from .robot import RobotAttack
from .renegotiation import RenegotiationAttack
from .freak import FreakAttack
from .logjam import LogjamAttack
